version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install awscli --upgrade
      - npm install
  build:
    commands:
      - git clone https://github.com/$GIT_HUB_COLLECTIONS_REPO data
      - npm run build
      - aws s3 sync docs/ $COLLECTIONS_BROWSER_S3_BUCKET --delete --acl=bucket-owner-full-control
