version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install awscli --upgrade
      - npm install
  build:
    commands:
      - bash _scripts/build.sh
      - bash _scripts/deploy.sh
      - mv dist docs
      - git config user.email "codebuild@aws.amazon.com"
      - git config user.name "AWS CodeBuild"
      - git remote set-url origin https://$GIT_HUB_AUTH_USER:$GIT_HUB_AUTH_TOKEN@github.com/$GIT_HUB_REPO
      - git add docs
      - git commit -m [CodeBuild]
      - git push origin HEAD:master