version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install awscli --upgrade
      - npm install
  build:
    commands:
      - git clone $GIT_HUB_COLLECTIONS_REPO data
      - npm run build
      - aws s3 sync docs/ s3://collections.sentinel-hub.com/ --delete --acl=bucket-owner-full-control
